services:
  postgres_url_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456 
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  url_shortener_api:
    build: .
    ports:
      - '3010:3010'
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres_url_db:5432/url_shortener
    depends_on:
      postgres_url_db:
        condition: service_healthy
volumes:
  pgdata: